env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - brew update
  - brew install swiftlint
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
script: 
  - pod lib lint --allow-warnings
  - swiftlint
  - xcodebuild test -project NibLoader.xcodeproj -scheme NibLoader-iOS -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty -c
  - xcodebuild test -project NibLoader.xcodeproj -scheme NibLoader-macOS -destination 'platform=OS X' | xcpretty -c
  - xcodebuild test -project NibLoader.xcodeproj -scheme NibLoader-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'NibLoader' 
